admin_link_config:
    path: omnibus/configuration
    methods: [GET]
    defaults:
      _controller: 'Omnibus\Controller\MenuController::menuAction'
      _legacy_controller: 'OmnibusEuFreeController'
      _legacy_link: 'OmnibusEuFreeController'